version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: grafana_user    
      POSTGRES_PASSWORD: grafana_pass 
      POSTGRES_DB: grafana_db_postgres         
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    networks:
      - monitoring_system

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass     
      MYSQL_DATABASE: grafana_db_mysql      
      MYSQL_USER: grafana_user       
      MYSQL_PASSWORD: grafana_pass    
      TZ: Europe/Moscow
    ports:
      - "3306:3306"
    networks:
      - monitoring_system

networks:
  monitoring_system:
    external: true
